export const URLS_AMAZON = {
  AMAZON: "https://amzn.to/47LAqoi",
  MESKO: "https://amzn.to/47FepHU",
  UFESA: "https://amzn.to/47FEMgL",
  CECOTEC: "https://amzn.to/4aZHwsa",
  HOMLEE: "https://amzn.to/3OaMFnn",
  BOMANN: "https://amzn.to/3SmfeAU",
  FAMILY_CARE: "https://amzn.to/4aZCJXL",
  MELLERWARE: "https://amzn.to/3S2pInK",
  KENWOOD: "https://amzn.to/3OasgyZ",
  PRIXTON: "https://amzn.to/3u0wulQ",
  KITCHEN: "https://amzn.to/3vNfX56",
  HAMILTON: "https://amzn.to/3HqDAmU",
  SMEG: "https://amzn.to/48WcSy2",
};
